import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppHeader } from "@/components/header";
import { AppMenu } from "@/components/menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex w-full relative">
          <div style={{flex: '0 1 240px', left: '0', top: '0', position: 'fixed'}}>
            <AppHeader />
            <AppMenu />
          </div>
          <main className="flex-1 overflow-x-auto" style={{marginLeft: '240px', position: 'relative',width: 'calc(100% - 240px)'}}>{children}</main>
        </div>
      </body>
    </html>
  );
}
